### ISSUE TITLE
Private API tokens exposed!

### ISSUE THREAD

**Issue by randomir** [tonandr/dwave_qc#1]
Your D-Wave API access tokens are exposed in https://github.com/tonandr/dwave_qc/commit/109c3388946ade3c5f8f48923d0939c2ee80f4f5.

You removed them in master, but they are still in git.

To prevent misuse, please invalidate them through the Leap dashboard.

For security reasons, D-Wave API access token can be stored in a [configuration file or environment variable](https://docs.ocean.dwavesys.com/projects/cloud-client/en/latest/intro.html#configuration), and it's picked-up automatically by the cloud client and `DWaveSampler`.

**Comment by tonandr** [comment]
Thank you for indicating my fault.
I invalidated this token.
